### ISSUE TITLE
AttributeError with GNU Radio 3.7.8

### ISSUE THREAD

**Issue by cyrozap** [funoverip/gr-cc1111#1]
I've built this module but it doesn't work on the latest stable GNU Radio version. Here's the error I'm getting:

```
Traceback (most recent call last):
  File "./send_packet.py", line 38, in <module>
    rf = cc1111_packet_sender.cc1111_packet_sender()
  File "/<path>/cc1111_packet_sender.py", line 116, in __init__
    source_queue=data
  File "/usr/lib/python2.7/site-packages/cc1111/cc1111_packet.py", line 140, in __init__
    gr.io_signature(1, 1, packet_source._hb.output_signature().sizeof_stream_item(0)) # Output signature
  File "/usr/lib/python2.7/site-packages/gnuradio/gr/hier_block2.py", line 92, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'hier_block2_sptr' object has no attribute '_hb'
```

From this, it appears as though `packet_source` does not have an `_hb` attribute. I'm not sure what `_hb` was supposed to be, so I don't know how to fix it myself. I'm also not entirely sure if it is or isn't an implementation error on my part. `data` is `gr.message_queue(2)` and `cc1111_packet_sender` is the name of my flow graph.

If it helps, here's the what `dir(packet_source)` gives me:

```
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_access_code', '_add_crc', '_bits_per_symbol', '_do_whitening', '_impl', '_msgq_out', '_pad_for_usrp', '_preamble', '_samples_per_symbol', 'connect', 'disconnect', 'dot_graph', 'message_port_register_hier_in', 'message_port_register_hier_out', 'msg_connect', 'msg_disconnect', 'send_pkt']
```

**Comment by cyrozap** [comment]
I was able to fix the issue with [this patch](https://paste.fedoraproject.org/279827/14449674/), but I'm not sure if that's the proper way to do it.

**Comment by funoverip** [comment]
Thank you for the feedback cyrozap !

**Comment by zemunkh** [comment]
thanks buddy

**Comment by righel** [comment]
I have the same issue and the pastebin link expired...
![image](https://user-images.githubusercontent.com/1659902/45364106-abbd1500-b5af-11e8-84fa-80482db8b584.png)


WHO WERE YOU, **@cyrozap**?
WHAT DID YOU SEE?!

**Comment by righel** [comment]
Hey, figured it out. My solution was to change this line:
https://github.com/funoverip/gr-cc1111/blob/e6b5eb045aa002d78345bb8aaa01cb6480efccfd/src/gr-cc1111/python/cc1111_packet.py#L139
to:
`gr.io_signature(1, 1, packet_source.output_signature().sizeof_stream_item(0)) # Output signature`

Thanks for the library! :)
