### ISSUE TITLE
cmake error with gnuradio installed with apt-get

### ISSUE THREAD

**Issue by SpaceTeddy** [funoverip/gr-cc1111#2]
Dear sirs,

install failed with the following configuration:

gnuradio -> sudo apt-get install gnuradio
gr-cc1111 git clone

any idear to fix this? thanks a lot.
## error log:

ubuntu@ubuntu:~/rf/gr-cc1111/src/gr-cc1111/build$ cmake ../
-- Build type not specified: defaulting to release.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Error at CMakeLists.txt:93 (find_package):
  By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Gnuradio",
  but CMake did not find one.

  Could not find a package configuration file provided by "Gnuradio"
  (requested version 3.7.2.1) with any of the following names:

```
GnuradioConfig.cmake
gnuradio-config.cmake
```

  Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
  "Gnuradio_DIR" to a directory containing one of the above files.  If
  "Gnuradio" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!

**Comment by funoverip** [comment]
Hi,

I've never installed GnuRadio using apt-get. I always compile it.
Try to give the gnuradio installation path to cmake. Ex:

cmake -DCMAKE_INSTALL_PREFIX=/usr/local/path_to_gnuradio ../

or 

cmake -DCMAKE_PREFIX_PATH=/usr/local/path_to_gnuradio ../
