### ISSUE TITLE
SWIG Issues

### ISSUE THREAD

**Issue by NoobieDog** [funoverip/gr-cc1111#3]
Hi, 

Im struggling to get this modual to work correctly, done as requested in the install guide. this is on a FRESH install of Kali 2017.1 vm,

Thanks for any help, really appreciate it.

> root@kali:~/Documents/gr-cc1111/testing-scripts# python hackrf_receiver.py 
> Traceback (most recent call last):
>   File "hackrf_receiver.py", line 6, in <module>
>     import grc_cc1111_hackrf_receiver
>   File "/root/Documents/gr-cc1111/testing-scripts/grc_cc1111_hackrf_receiver.py", line 18, in <module>
>     import cc1111
>   File "/usr/local/lib/python2.7/dist-packages/cc1111/__init__.py", line 45, in <module>
>     from cc1111_swig import *
>   File "/usr/local/lib/python2.7/dist-packages/cc1111/cc1111_swig.py", line 21, in <module>
>     _cc1111_swig = swig_import_helper()
>   File "/usr/local/lib/python2.7/dist-packages/cc1111/cc1111_swig.py", line 20, in swig_import_helper
>     return importlib.import_module('_cc1111_swig')
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named _cc1111_swig

**Comment by NoobieDog** [comment]
fixed ;) reinstalled SWIG and recompiled ;D

**Comment by funoverip** [comment]
Thanks for the feedback :)
